services:
  db:
    image: ankane/pgvector:latest
    container_name: eventflow_postgres
    environment:
      POSTGRES_USER: arif
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: eventflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata: