name: Build Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'gateway/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'gateway/**'
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: eventflow
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step A: Build and export cache (Runs even if push would have failed)
      - name: Build and Cache Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: false # Do not push yet, just build and cache
          tags: |
            ghcr.io/${{ github.repository_owner }}/gateway-service:latest
            ghcr.io/${{ github.repository_owner }}/gateway-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Step B: Push the pre-built image (If this fails, your cache from Step A is already safe)
      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gateway-service:latest
            ghcr.io/${{ github.repository_owner }}/gateway-service:${{ github.sha }}
          cache-from: type=gha
